# Generated by Django 3.2.6 on 2021-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project2',
            name='url',
        ),
        migrations.AlterField(
            model_name='project2',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project2',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project2',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
